### ISSUE TITLE
Need a way to restrict space groups in spacegroup.py

### ISSUE THREAD

**Issue by InfluenceFunctional** [alexhernandezgarcia/gflownet#179]
Need to pass a list of space group labels or numbers to spacegroup.py and have it restrict generation to only these groups. 

I don't want to break it / make a mess. Assuming there's an elegant way to do it in maybe in get_mask_invalid_actions_forward(), but I haven't been able to run it an figure out the logic yet.

**Comment by alexhernandezgarcia** [comment]
One not too inelegant way would be the following:
1. Add a new argument for the class `SpaceGroup` that allows you to select (or exclude) a subset of space groups.
2. Modify [`_get_space_group()`](https://github.com/alexhernandezgarcia/gflownet/blob/main/gflownet/envs/crystals/spacegroup.py#L38) such that you can [pass it](https://github.com/alexhernandezgarcia/gflownet/blob/main/gflownet/envs/crystals/spacegroup.py#L88) the information about the selection and it will return only the subset.

In principle, and unless I am missing something (possible), everything else should be all set with these changes since:
- `self.space_groups` will be the reduced set of space groups.
- `self.n_space_groups` will just be the length of `self.space_groups`.

But that nothing else needs to be changed should be confirmed and tested, of course...

Other things to update:
- [config/env/crystals/spacegroup.yaml](https://github.com/alexhernandezgarcia/gflownet/blob/main/config/env/crystals/spacegroup.yaml)
- [tests/gflownet/envs/test_spacegroup.py](https://github.com/alexhernandezgarcia/gflownet/blob/main/tests/gflownet/envs/test_spacegroup.py)
- The pieces of code/config that interact with the space group in the crystal environment.

**Comment by alexhernandezgarcia** [comment]
I addressed this issue in PR https://github.com/alexhernandezgarcia/gflownet/pull/223
